/**
 * Git Large File Storage (LFS) management utilities
 * Handles automatic LFS tracking for large files in GitCMS
 */

export interface LFSConfig {
  /** Enabled file extensions for LFS tracking */
  enabledExtensions: string[];
  /** File size threshold in bytes (default: 50MB) */
  sizeThreshold: number;
  /** Whether to auto-track large files */
  autoTrack: boolean;
  /** Custom patterns for LFS tracking */
  customPatterns: string[];
}

export interface LFSStatus {
  /** Whether LFS is enabled for the repository */
  isEnabled: boolean;
  /** Current .gitattributes rules */
  rules: LFSRule[];
  /** Files that should be tracked by LFS */
  suggestedFiles: string[];
  /** Total size of LFS-tracked files */
  trackedSize: number;
}

export interface LFSRule {
  /** File pattern (e.g., "*.psd", "*.zip") */
  pattern: string;
  /** LFS attributes */
  attributes: string;
  /** Human-readable description */
  description: string;
  /** Whether this rule was auto-generated */
  autoGenerated: boolean;
}

export interface LFSFileAnalysis {
  /** File path */
  path: string;
  /** File size in bytes */
  size: number;
  /** File extension */
  extension: string;
  /** Whether file should be LFS tracked */
  shouldTrack: boolean;
  /** Reason for tracking recommendation */
  reason: string;
}

/**
 * Default LFS configuration for common media and binary files
 */
export const DEFAULT_LFS_CONFIG: LFSConfig = {
  enabledExtensions: [
    // Images
    'psd',
    'psb',
    'tiff',
    'tif',
    'bmp',
    'raw',
    'cr2',
    'nef',
    'arw',
    'dng',
    // Videos
    'mp4',
    'avi',
    'mov',
    'wmv',
    'flv',
    'webm',
    'mkv',
    'm4v',
    '3gp',
    // Audio
    'mp3',
    'wav',
    'flac',
    'aac',
    'ogg',
    'wma',
    'm4a',
    // Documents
    'pdf',
    'doc',
    'docx',
    'ppt',
    'pptx',
    'xls',
    'xlsx',
    // Archives
    'zip',
    'rar',
    '7z',
    'tar',
    'gz',
    'bz2',
    // 3D/CAD
    'obj',
    'fbx',
    'blend',
    'max',
    'c4d',
    'dwg',
    // Fonts
    'ttf',
    'otf',
    'woff',
    'woff2',
    // Other binary
    'exe',
    'dmg',
    'pkg',
    'deb',
    'rpm',
  ],
  sizeThreshold: 50 * 1024 * 1024, // 50MB
  autoTrack: true,
  customPatterns: [],
};

/**
 * Predefined LFS rules for common file types
 */
export const COMMON_LFS_RULES: LFSRule[] = [
  {
    pattern: '*.psd',
    attributes: 'filter=lfs diff=lfs merge=lfs -text',
    description: 'Adobe Photoshop Documents',
    autoGenerated: true,
  },
  {
    pattern: '*.ai',
    attributes: 'filter=lfs diff=lfs merge=lfs -text',
    description: 'Adobe Illustrator Files',
    autoGenerated: true,
  },
  {
    pattern: '*.zip',
    attributes: 'filter=lfs diff=lfs merge=lfs -text',
    description: 'Compressed Archives',
    autoGenerated: true,
  },
  {
    pattern: '*.mp4',
    attributes: 'filter=lfs diff=lfs merge=lfs -text',
    description: 'Video Files (MP4)',
    autoGenerated: true,
  },
  {
    pattern: '*.mov',
    attributes: 'filter=lfs diff=lfs merge=lfs -text',
    description: 'Video Files (QuickTime)',
    autoGenerated: true,
  },
  {
    pattern: '*.pdf',
    attributes: 'filter=lfs diff=lfs merge=lfs -text',
    description: 'PDF Documents',
    autoGenerated: true,
  },
  {
    pattern: '*.ttf',
    attributes: 'filter=lfs diff=lfs merge=lfs -text',
    description: 'TrueType Fonts',
    autoGenerated: true,
  },
  {
    pattern: '*.woff',
    attributes: 'filter=lfs diff=lfs merge=lfs -text',
    description: 'Web Fonts (WOFF)',
    autoGenerated: true,
  },
  {
    pattern: '*.woff2',
    attributes: 'filter=lfs diff=lfs merge=lfs -text',
    description: 'Web Fonts (WOFF2)',
    autoGenerated: true,
  },
];

/**
 * Git LFS Manager for GitCMS
 * Handles automatic LFS configuration and file tracking
 */
export class GitLFSManager {
  private config: LFSConfig;
  private githubClient: any; // GitHubApiClient
  private owner: string;
  private repo: string;

  constructor(githubClient: any, owner: string, repo: string, config?: Partial<LFSConfig>) {
    this.githubClient = githubClient;
    this.owner = owner;
    this.repo = repo;
    this.config = { ...DEFAULT_LFS_CONFIG, ...config };
  }

  /**
   * Analyze repository for LFS requirements
   */
  async analyzeLFSRequirements(): Promise<LFSStatus> {
    try {
      // Check if .gitattributes exists
      const hasGitAttributes = await this.githubClient.fileExists('.gitattributes');

      // Get current .gitattributes content if it exists
      let currentRules: LFSRule[] = [];
      if (hasGitAttributes) {
        currentRules = await this.parseGitAttributes();
      }

      // Scan repository for large files
      const suggestedFiles = await this.scanForLargeFiles();

      // Calculate total tracked size
      const trackedSize = await this.calculateTrackedSize(currentRules);

      return {
        isEnabled: hasGitAttributes && currentRules.length > 0,
        rules: currentRules,
        suggestedFiles,
        trackedSize,
      };
    } catch (error) {
      console.error('Error analyzing LFS requirements:', error);
      return {
        isEnabled: false,
        rules: [],
        suggestedFiles: [],
        trackedSize: 0,
      };
    }
  }

  /**
   * Initialize LFS tracking for the repository
   */
  async initializeLFS(customRules?: LFSRule[]): Promise<void> {
    try {
      // Combine default rules with custom rules
      const allRules = [...COMMON_LFS_RULES];

      if (customRules) {
        allRules.push(...customRules);
      }

      // Add rules based on configuration
      for (const extension of this.config.enabledExtensions) {
        const existingRule = allRules.find(rule => rule.pattern === `*.${extension}`);
        if (!existingRule) {
          allRules.push({
            pattern: `*.${extension}`,
            attributes: 'filter=lfs diff=lfs merge=lfs -text',
            description: `${extension.toUpperCase()} files`,
            autoGenerated: true,
          });
        }
      }

      // Generate .gitattributes content
      const gitAttributesContent = this.generateGitAttributesContent(allRules);

      // Check if .gitattributes exists
      let existingSha: string | undefined;
      try {
        const existing = await this.githubClient.getFile('.gitattributes');
        existingSha = existing.sha;
      } catch (error) {
        // File doesn't exist, which is fine
      }

      // Create or update .gitattributes
      await this.githubClient.updateFile(
        '.gitattributes',
        gitAttributesContent,
        existingSha ? 'Update Git LFS configuration' : 'Initialize Git LFS configuration',
        existingSha
      );

      console.log('LFS initialized successfully');
    } catch (error) {
      throw new Error(
        `Failed to initialize LFS: ${error instanceof Error ? error.message : 'Unknown error'}`
      );
    }
  }

  /**
   * Add LFS tracking for specific file patterns
   */
  async addLFSPattern(pattern: string, description?: string): Promise<void> {
    try {
      const currentRules = await this.parseGitAttributes();

      // Check if pattern already exists
      if (currentRules.some(rule => rule.pattern === pattern)) {
        console.log(`Pattern ${pattern} is already tracked by LFS`);
        return;
      }

      // Add new rule
      const newRule: LFSRule = {
        pattern,
        attributes: 'filter=lfs diff=lfs merge=lfs -text',
        description: description || `${pattern} files`,
        autoGenerated: false,
      };

      currentRules.push(newRule);

      // Update .gitattributes
      const gitAttributesContent = this.generateGitAttributesContent(currentRules);

      const existing = await this.githubClient.getFile('.gitattributes');
      await this.githubClient.updateFile(
        '.gitattributes',
        gitAttributesContent,
        `Add LFS tracking for ${pattern}`,
        existing.sha
      );

      console.log(`Added LFS tracking for ${pattern}`);
    } catch (error) {
      throw new Error(
        `Failed to add LFS pattern: ${error instanceof Error ? error.message : 'Unknown error'}`
      );
    }
  }

  /**
   * Remove LFS tracking for specific file patterns
   */
  async removeLFSPattern(pattern: string): Promise<void> {
    try {
      const currentRules = await this.parseGitAttributes();

      // Filter out the pattern
      const updatedRules = currentRules.filter(rule => rule.pattern !== pattern);

      if (updatedRules.length === currentRules.length) {
        console.log(`Pattern ${pattern} was not found in LFS tracking`);
        return;
      }

      // Update .gitattributes
      const gitAttributesContent = this.generateGitAttributesContent(updatedRules);

      const existing = await this.githubClient.getFile('.gitattributes');
      await this.githubClient.updateFile(
        '.gitattributes',
        gitAttributesContent,
        `Remove LFS tracking for ${pattern}`,
        existing.sha
      );

      console.log(`Removed LFS tracking for ${pattern}`);
    } catch (error) {
      throw new Error(
        `Failed to remove LFS pattern: ${error instanceof Error ? error.message : 'Unknown error'}`
      );
    }
  }

  /**
   * Analyze files for LFS tracking recommendations
   */
  async analyzeFiles(filePaths: string[]): Promise<LFSFileAnalysis[]> {
    const analyses: LFSFileAnalysis[] = [];

    for (const path of filePaths) {
      try {
        const file = await this.githubClient.getFile(path);
        const extension = this.getFileExtension(path);

        const analysis: LFSFileAnalysis = {
          path,
          size: file.size,
          extension,
          shouldTrack: this.shouldTrackFile(path, file.size),
          reason: this.getTrackingReason(path, file.size),
        };

        analyses.push(analysis);
      } catch (error) {
        // File might not exist or be inaccessible
        console.warn(`Could not analyze file ${path}:`, error);
      }
    }

    return analyses;
  }

  /**
   * Parse existing .gitattributes file
   */
  private async parseGitAttributes(): Promise<LFSRule[]> {
    try {
      const content = await this.githubClient.getFileContent('.gitattributes');
      const rules: LFSRule[] = [];

      const lines = content.split('\n');
      for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#')) {
          const parts = trimmed.split(/\s+/);
          if (parts.length >= 2 && parts.includes('filter=lfs')) {
            const pattern = parts[0];
            const attributes = parts.slice(1).join(' ');

            rules.push({
              pattern,
              attributes,
              description: this.getPatternDescription(pattern),
              autoGenerated: false,
            });
          }
        }
      }

      return rules;
    } catch (error) {
      return [];
    }
  }

  /**
   * Generate .gitattributes content from rules
   */
  private generateGitAttributesContent(rules: LFSRule[]): string {
    const header = `# Git LFS Configuration for GitCMS
# This file specifies which files should be stored using Git Large File Storage (LFS)
# Generated automatically by GitCMS - modify with care

`;

    const ruleLines = rules.map(rule => `${rule.pattern} ${rule.attributes}`).join('\n');

    return header + ruleLines + '\n';
  }

  /**
   * Scan repository for large files that should be LFS tracked
   */
  private async scanForLargeFiles(): Promise<string[]> {
    const suggestedFiles: string[] = [];

    try {
      // Get all files in media directory (if exists)
      const mediaDirectories = ['media', '.gitcms/media', 'public/media', 'assets/media'];

      for (const dir of mediaDirectories) {
        try {
          const files = await this.githubClient.getDirectory(dir);

          for (const file of files) {
            if (file.type === 'file' && this.shouldTrackFile(file.path, file.size)) {
              suggestedFiles.push(file.path);
            }
          }
        } catch (error) {
          // Directory might not exist
        }
      }
    } catch (error) {
      console.warn('Error scanning for large files:', error);
    }

    return suggestedFiles;
  }

  /**
   * Calculate total size of LFS-tracked files
   */
  private async calculateTrackedSize(rules: LFSRule[]): Promise<number> {
    // This would require scanning all files and matching patterns
    // For now, return 0 as it's expensive to calculate
    return 0;
  }

  /**
   * Check if a file should be tracked by LFS
   */
  private shouldTrackFile(path: string, size: number): boolean {
    const extension = this.getFileExtension(path);

    // Check size threshold
    if (size > this.config.sizeThreshold) {
      return true;
    }

    // Check extension list
    if (this.config.enabledExtensions.includes(extension.toLowerCase())) {
      return true;
    }

    return false;
  }

  /**
   * Get reason why file should be tracked
   */
  private getTrackingReason(path: string, size: number): string {
    const extension = this.getFileExtension(path);

    if (size > this.config.sizeThreshold) {
      return `Large file (${this.formatFileSize(size)})`;
    }

    if (this.config.enabledExtensions.includes(extension.toLowerCase())) {
      return `Binary file type (.${extension})`;
    }

    return 'Recommended for LFS';
  }

  /**
   * Get file extension from path
   */
  private getFileExtension(path: string): string {
    const parts = path.split('.');
    return parts.length > 1 ? parts[parts.length - 1] : '';
  }

  /**
   * Get description for a pattern
   */
  private getPatternDescription(pattern: string): string {
    const extension = pattern.replace('*.', '');

    const descriptions: Record<string, string> = {
      psd: 'Adobe Photoshop Documents',
      ai: 'Adobe Illustrator Files',
      zip: 'Compressed Archives',
      rar: 'RAR Archives',
      '7z': '7-Zip Archives',
      mp4: 'MP4 Video Files',
      mov: 'QuickTime Video Files',
      avi: 'AVI Video Files',
      pdf: 'PDF Documents',
      ttf: 'TrueType Fonts',
      otf: 'OpenType Fonts',
      woff: 'Web Fonts (WOFF)',
      woff2: 'Web Fonts (WOFF2)',
    };

    return descriptions[extension] || `${extension.toUpperCase()} files`;
  }

  /**
   * Format file size in human-readable format
   */
  private formatFileSize(bytes: number): string {
    const units = ['B', 'KB', 'MB', 'GB'];
    let value = bytes;
    let unitIndex = 0;

    while (value >= 1024 && unitIndex < units.length - 1) {
      value /= 1024;
      unitIndex++;
    }

    return `${value.toFixed(1)} ${units[unitIndex]}`;
  }
}

/**
 * LFS utility functions
 */
export const LFSUtils = {
  /**
   * Check if a file should be LFS tracked based on common patterns
   */
  shouldUseLFS(filePath: string, fileSize?: number): boolean {
    const extension = filePath.split('.').pop()?.toLowerCase() || '';

    // Check common binary extensions
    const lfsExtensions = DEFAULT_LFS_CONFIG.enabledExtensions;
    if (lfsExtensions.includes(extension)) {
      return true;
    }

    // Check size threshold if provided
    if (fileSize && fileSize > DEFAULT_LFS_CONFIG.sizeThreshold) {
      return true;
    }

    return false;
  },

  /**
   * Generate LFS pattern from file extension
   */
  generatePattern(extension: string): string {
    return `*.${extension.toLowerCase()}`;
  },

  /**
   * Validate LFS pattern
   */
  isValidPattern(pattern: string): boolean {
    return /^\*\.[a-zA-Z0-9]+$/.test(pattern) || pattern.includes('/');
  },

  /**
   * Get recommended LFS rules for common media types
   */
  getMediaLFSRules(): LFSRule[] {
    return [
      {
        pattern: '*.psd',
        attributes: 'filter=lfs diff=lfs merge=lfs -text',
        description: 'Photoshop Files',
        autoGenerated: true,
      },
      {
        pattern: '*.ai',
        attributes: 'filter=lfs diff=lfs merge=lfs -text',
        description: 'Illustrator Files',
        autoGenerated: true,
      },
      {
        pattern: '*.mp4',
        attributes: 'filter=lfs diff=lfs merge=lfs -text',
        description: 'Video Files',
        autoGenerated: true,
      },
      {
        pattern: '*.zip',
        attributes: 'filter=lfs diff=lfs merge=lfs -text',
        description: 'Archives',
        autoGenerated: true,
      },
    ];
  },
};
